apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-foundry-sandbox
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-foundry.labels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
automountServiceAccountToken: false
