apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-foundry.fullname" . }}-operator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-foundry.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
